### ISSUE TITLE
Looks like we had the same idea

### ISSUE THREAD

**Issue by ZeusJunior** [NetroScript/backpack.tf-miscellaneous-extensions#1]
Hi,

I noticed this repo was last updated 3/4th of a year ago and decided to fork it and edit myself.
You must've noticed or its just a nice timing because today you added spells being marked on compare links which i just finished locally.

Thought it might be an idea to edit this together instead if you're interested. My steam link:
https://steamcommunity.com/profiles/76561198144346135

**Comment by ZeusJunior** [comment]
Just heard from glen that you're Jack from the bptf discord

**Comment by NetroScript** [comment]
You are correct, I read your message in discord, first I wanted to tell you how you would do it until I realised you forked my userscript and talked about it so I added it myself. And forking is nothing wrong, although I want to mention I more or less keep all my userscripts up to date, only that this script didn't need any updates (no new skins, no feature requests in the issues). So you can go ahead and add features if you want, but at least if you want to keep it up with the main branch (should I do changes) it would be less work for you to PR instead of updating your fork everytime. (But the license is Apache License 2.0 so you can do what you think is better)
